-- Migration: add game_format to position_instructions + seed jeugd spelvormen
-- Run in Supabase SQL editor

-- 1. Voeg game_format kolom toe (default '11v11' voor bestaande regels)
ALTER TABLE position_instructions
  ADD COLUMN IF NOT EXISTS game_format text NOT NULL DEFAULT '11v11';

-- 2. Vervang unieke constraint: (formation, position_index) → (game_format, formation, position_index)
ALTER TABLE position_instructions
  DROP CONSTRAINT IF EXISTS position_instructions_formation_position_index_key;

ALTER TABLE position_instructions
  ADD CONSTRAINT position_instructions_game_format_formation_position_idx
  UNIQUE (game_format, formation, position_index);

-- 3. Seed systeem-instructies uit import_all_spelvormen.csv
INSERT INTO position_instructions (game_format, formation, position_index, position_name, title, general_tips, with_ball, without_ball)
VALUES
  -- 4v4 · 2-2
  ('4v4','2-2',0,'V1','Verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('4v4','2-2',1,'V2','Verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('4v4','2-2',2,'A1','Aanvallers',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  ('4v4','2-2',3,'A2','Aanvallers',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  -- 4v4 · 1-2-1
  ('4v4','1-2-1',0,'ACHT','Achter',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('4v4','1-2-1',1,'LM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('4v4','1-2-1',2,'RM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('4v4','1-2-1',3,'SP','Spits',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  -- 5v5 · 2-2
  ('5v5','2-2',0,'Keeper','Keeper',
   ARRAY['Coach de verdediging','Blijf aanspeelbaar','Speel mee als extra veldspeler'],
   ARRAY['Kies korte opbouw','Speel via verdedigers','Open aannemen'],
   ARRAY['Sta voor je goal','Anticipeer op diepte','Kom uit bij lange bal']),
  ('5v5','2-2',1,'V1','Verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('5v5','2-2',2,'V2','Verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('5v5','2-2',3,'A1','Aanvallers',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  ('5v5','2-2',4,'A2','Aanvallers',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  -- 5v5 · 1-2-1
  ('5v5','1-2-1',0,'Keeper','Keeper',
   ARRAY['Coach de verdediging','Blijf aanspeelbaar','Speel mee als extra veldspeler'],
   ARRAY['Kies korte opbouw','Speel via verdedigers','Open aannemen'],
   ARRAY['Sta voor je goal','Anticipeer op diepte','Kom uit bij lange bal']),
  ('5v5','1-2-1',1,'CV','Centrale verdediger',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('5v5','1-2-1',2,'LM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('5v5','1-2-1',3,'RM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('5v5','1-2-1',4,'SP','Spits',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  -- 6v6 · 2-2-1
  ('6v6','2-2-1',0,'Keeper','Keeper',
   ARRAY['Coach de verdediging','Blijf aanspeelbaar','Speel mee als extra veldspeler'],
   ARRAY['Kies korte opbouw','Speel via verdedigers','Open aannemen'],
   ARRAY['Sta voor je goal','Anticipeer op diepte','Kom uit bij lange bal']),
  ('6v6','2-2-1',1,'CVL','Centrale verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('6v6','2-2-1',2,'CVR','Centrale verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('6v6','2-2-1',3,'LM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('6v6','2-2-1',4,'RM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('6v6','2-2-1',5,'SP','Spits',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  -- 6v6 · 1-3-1
  ('6v6','1-3-1',0,'Keeper','Keeper',
   ARRAY['Coach de verdediging','Blijf aanspeelbaar','Speel mee als extra veldspeler'],
   ARRAY['Kies korte opbouw','Speel via verdedigers','Open aannemen'],
   ARRAY['Sta voor je goal','Anticipeer op diepte','Kom uit bij lange bal']),
  ('6v6','1-3-1',1,'CV','Centrale verdediger',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('6v6','1-3-1',2,'LM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('6v6','1-3-1',3,'CM','Centrale middenvelder',
   ARRAY['Spel verdelen','Overzicht houden','Coachen'],
   ARRAY['Tempo bepalen','Verleggen','Steekpass zoeken'],
   ARRAY['Balzijde druk','Ruimte midden dicht','Verdediging helpen']),
  ('6v6','1-3-1',4,'RM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('6v6','1-3-1',5,'SP','Spits',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  -- 7v7 · 2-3-1
  ('7v7','2-3-1',0,'Keeper','Keeper',
   ARRAY['Coach de verdediging','Blijf aanspeelbaar','Speel mee als extra veldspeler'],
   ARRAY['Kies korte opbouw','Speel via verdedigers','Open aannemen'],
   ARRAY['Sta voor je goal','Anticipeer op diepte','Kom uit bij lange bal']),
  ('7v7','2-3-1',1,'CVL','Centrale verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('7v7','2-3-1',2,'CVR','Centrale verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('7v7','2-3-1',3,'LM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('7v7','2-3-1',4,'CM','Centrale middenvelder',
   ARRAY['Spel verdelen','Overzicht houden','Coachen'],
   ARRAY['Tempo bepalen','Verleggen','Steekpass zoeken'],
   ARRAY['Balzijde druk','Ruimte midden dicht','Verdediging helpen']),
  ('7v7','2-3-1',5,'RM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('7v7','2-3-1',6,'SP','Spits',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  -- 7v7 · 3-2-1
  ('7v7','3-2-1',0,'Keeper','Keeper',
   ARRAY['Coach de verdediging','Blijf aanspeelbaar','Speel mee als extra veldspeler'],
   ARRAY['Kies korte opbouw','Speel via verdedigers','Open aannemen'],
   ARRAY['Sta voor je goal','Anticipeer op diepte','Kom uit bij lange bal']),
  ('7v7','3-2-1',1,'LV','Backs',
   ARRAY['Zijkant bewaken','Meeschuiven in aanval','Samenwerken met middenvelder'],
   ARRAY['Breed staan','Overlap/inschuiven','Voorzet of terugspelen'],
   ARRAY['Buitenkant dicht','Tegenstander naar buiten','Terug sprinten']),
  ('7v7','3-2-1',2,'CV','Centrale verdediger',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('7v7','3-2-1',3,'RV','Backs',
   ARRAY['Zijkant bewaken','Meeschuiven in aanval','Samenwerken met middenvelder'],
   ARRAY['Breed staan','Overlap/inschuiven','Voorzet of terugspelen'],
   ARRAY['Buitenkant dicht','Tegenstander naar buiten','Terug sprinten']),
  ('7v7','3-2-1',4,'LM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('7v7','3-2-1',5,'RM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('7v7','3-2-1',6,'SP','Spits',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  -- 8v8 · 3-3-1
  ('8v8','3-3-1',0,'Keeper','Keeper',
   ARRAY['Coach de verdediging','Blijf aanspeelbaar','Speel mee als extra veldspeler'],
   ARRAY['Kies korte opbouw','Speel via verdedigers','Open aannemen'],
   ARRAY['Sta voor je goal','Anticipeer op diepte','Kom uit bij lange bal']),
  ('8v8','3-3-1',1,'LV','Backs',
   ARRAY['Zijkant bewaken','Meeschuiven in aanval','Samenwerken met middenvelder'],
   ARRAY['Breed staan','Overlap/inschuiven','Voorzet of terugspelen'],
   ARRAY['Buitenkant dicht','Tegenstander naar buiten','Terug sprinten']),
  ('8v8','3-3-1',2,'CV','Centrale verdediger',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('8v8','3-3-1',3,'RV','Backs',
   ARRAY['Zijkant bewaken','Meeschuiven in aanval','Samenwerken met middenvelder'],
   ARRAY['Breed staan','Overlap/inschuiven','Voorzet of terugspelen'],
   ARRAY['Buitenkant dicht','Tegenstander naar buiten','Terug sprinten']),
  ('8v8','3-3-1',4,'LM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('8v8','3-3-1',5,'CM','Centrale middenvelder',
   ARRAY['Spel verdelen','Overzicht houden','Coachen'],
   ARRAY['Tempo bepalen','Verleggen','Steekpass zoeken'],
   ARRAY['Balzijde druk','Ruimte midden dicht','Verdediging helpen']),
  ('8v8','3-3-1',6,'RM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('8v8','3-3-1',7,'SP','Spits',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  -- 8v8 · 2-3-2
  ('8v8','2-3-2',0,'Keeper','Keeper',
   ARRAY['Coach de verdediging','Blijf aanspeelbaar','Speel mee als extra veldspeler'],
   ARRAY['Kies korte opbouw','Speel via verdedigers','Open aannemen'],
   ARRAY['Sta voor je goal','Anticipeer op diepte','Kom uit bij lange bal']),
  ('8v8','2-3-2',1,'CVL','Centrale verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('8v8','2-3-2',2,'CVR','Centrale verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('8v8','2-3-2',3,'LM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('8v8','2-3-2',4,'CM','Centrale middenvelder',
   ARRAY['Spel verdelen','Overzicht houden','Coachen'],
   ARRAY['Tempo bepalen','Verleggen','Steekpass zoeken'],
   ARRAY['Balzijde druk','Ruimte midden dicht','Verdediging helpen']),
  ('8v8','2-3-2',5,'RM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('8v8','2-3-2',6,'SP1','Spitsen',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  ('8v8','2-3-2',7,'SP2','Spitsen',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  -- 9v9 · 3-3-2
  ('9v9','3-3-2',0,'Keeper','Keeper',
   ARRAY['Coach de verdediging','Blijf aanspeelbaar','Speel mee als extra veldspeler'],
   ARRAY['Kies korte opbouw','Speel via verdedigers','Open aannemen'],
   ARRAY['Sta voor je goal','Anticipeer op diepte','Kom uit bij lange bal']),
  ('9v9','3-3-2',1,'LV','Backs',
   ARRAY['Zijkant bewaken','Meeschuiven in aanval','Samenwerken met middenvelder'],
   ARRAY['Breed staan','Overlap/inschuiven','Voorzet of terugspelen'],
   ARRAY['Buitenkant dicht','Tegenstander naar buiten','Terug sprinten']),
  ('9v9','3-3-2',2,'CV','Centrale verdediger',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('9v9','3-3-2',3,'RV','Backs',
   ARRAY['Zijkant bewaken','Meeschuiven in aanval','Samenwerken met middenvelder'],
   ARRAY['Breed staan','Overlap/inschuiven','Voorzet of terugspelen'],
   ARRAY['Buitenkant dicht','Tegenstander naar buiten','Terug sprinten']),
  ('9v9','3-3-2',4,'LM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('9v9','3-3-2',5,'CM','Centrale middenvelder',
   ARRAY['Spel verdelen','Overzicht houden','Coachen'],
   ARRAY['Tempo bepalen','Verleggen','Steekpass zoeken'],
   ARRAY['Balzijde druk','Ruimte midden dicht','Verdediging helpen']),
  ('9v9','3-3-2',6,'RM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('9v9','3-3-2',7,'SP1','Spitsen',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  ('9v9','3-3-2',8,'SP2','Spitsen',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  -- 9v9 · 2-3-3
  ('9v9','2-3-3',0,'Keeper','Keeper',
   ARRAY['Coach de verdediging','Blijf aanspeelbaar','Speel mee als extra veldspeler'],
   ARRAY['Kies korte opbouw','Speel via verdedigers','Open aannemen'],
   ARRAY['Sta voor je goal','Anticipeer op diepte','Kom uit bij lange bal']),
  ('9v9','2-3-3',1,'CVL','Centrale verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('9v9','2-3-3',2,'CVR','Centrale verdedigers',
   ARRAY['Houd het spel voor je','Coach medespelers','Schuif in bij ruimte'],
   ARRAY['Open aannemen','Inspelen middenveld','Indribbelen als het kan'],
   ARRAY['Druk op balhouder','Rugdekking','Diepte bewaken']),
  ('9v9','2-3-3',3,'LM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('9v9','2-3-3',4,'CM','Centrale middenvelder',
   ARRAY['Spel verdelen','Overzicht houden','Coachen'],
   ARRAY['Tempo bepalen','Verleggen','Steekpass zoeken'],
   ARRAY['Balzijde druk','Ruimte midden dicht','Verdediging helpen']),
  ('9v9','2-3-3',5,'RM','Middenvelders',
   ARRAY['Aanspeelbaar blijven','Veel bewegen','Helpen voor en achter'],
   ARRAY['Combineren','Actie naar voren','Kansen creëren'],
   ARRAY['Tegenpressie','Terugzakken','Passlijn sluiten']),
  ('9v9','2-3-3',6,'LVL','Vleugelspitsen',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  ('9v9','2-3-3',7,'SP','Spits',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren']),
  ('9v9','2-3-3',8,'RVR','Vleugelspitsen',
   ARRAY['Diepte zoeken','Bal vasthouden','Ruimte maken'],
   ARRAY['Kaatsen','Afwerken','Loopacties in diepte'],
   ARRAY['Eerste druk','Opbouw verstoren','Passlijn blokkeren'])
ON CONFLICT (game_format, formation, position_index) DO UPDATE SET
  position_name  = EXCLUDED.position_name,
  title          = EXCLUDED.title,
  general_tips   = EXCLUDED.general_tips,
  with_ball      = EXCLUDED.with_ball,
  without_ball   = EXCLUDED.without_ball;
