-- Tabel voor wedstrijd-specifieke instructie-afwijkingen
-- Voer dit uit in de Supabase SQL editor

CREATE TABLE IF NOT EXISTS match_position_instructions (
  id              bigint generated by default as identity primary key,
  match_id        bigint not null references matches(id) on delete cascade,
  formation       text not null,
  position_index  integer not null,
  position_name   text not null default '',
  title           text not null default '',
  general_tips    text[] not null default '{}',
  with_ball       text[] not null default '{}',
  without_ball    text[] not null default '{}',
  created_at      timestamptz not null default now(),

  -- Per wedstrijd maximaal één afwijking per positie
  unique (match_id, position_index)
);

-- Row Level Security (zelfde patroon als position_instructions)
ALTER TABLE match_position_instructions ENABLE ROW LEVEL SECURITY;

-- Iedereen binnen het team mag lezen
CREATE POLICY "Authenticated users can read match instructions"
  ON match_position_instructions
  FOR SELECT
  TO authenticated
  USING (true);

-- Alleen managers mogen schrijven (aanpassen in Supabase dashboard naar wens)
CREATE POLICY "Authenticated users can insert match instructions"
  ON match_position_instructions
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update match instructions"
  ON match_position_instructions
  FOR UPDATE
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can delete match instructions"
  ON match_position_instructions
  FOR DELETE
  TO authenticated
  USING (true);
